### ISSUE TITLE
WebPush using VAPID, error: illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by oozimok** [pennersr/shove#1]
Hello. Launched your project to send WebPush notifications. Checking sending using VAPID.
`curl  -i  --data '{"subscription": {"endpoint":"https://fcm.googleapis.com/fcm/send/cUGz6wv7OH0:APA91bHqwewkZFJ5oouwv0jZOYpwlsN3jg7n_83dnzbL5SCU5xNkTlcA9ozP0eOIHP3mkASJIkO1Idakd7j9atSugofRZEowo9N8YpTE9Qars6B6wCLkdpe5PKmNX0BP5fNTkKoRamZA","keys":{"auth": "ZmdkuTkUN0NTvsQqV7SUIA", "p256dh": "BBYQ484rGdY-HfEjAjGQUHH0k1KDmgsy6CnVcbr2l0SYZK1amCTVvNcbUCJazcawAMPOCcNkG0Omu3m2Scb9WoU"}}, "headers": {"ttl": 3600, "urgency": "high"}, "token": "token-1", "payload": {"hello":"world"}}' http://localhost:8322/api/push/webpush`

I see an error in the console:
`Shove error sending: illegal base64 data at input byte 0`

If you make an error in the p256dh key, an error will occur:
`Unmarshal Error: Public key is not a valid point on the curve`

That is, presumably the first error occurs below this line:
https://github.com/SherClockHolmes/webpush-go/blob/358c5ab877144efa20d3e889826d31d45ea3bec2/webpush.go#L101

There may be a problem with incorrectly passing JSON to the library.

What am I doing wrong? Does WebPush using VAPID work correctly for you?

**Comment by pennersr** [comment]
Definitely, it is in production pushing out a lot of notifications on a daily basis. 

If I take up your curl request as is, and execute it over here, I am receiving a proper HTTP 202 OK response. So the request looks fine to me.

How are you running the server side of things, did you provide the proper keys, like so:

```shove -webpush-vapid-public-key $${VAPID_PUBLIC_KEY} -webpush-vapid-private-key $${VAPID_PRIVATE_KEY}```

**Comment by oozimok** [comment]
Yes, the problem was determining the keys. Defining the keys through the `environment`, the problem is gone. Thank you for your work.
