### ISSUE TITLE
Redis queue docs

### ISSUE THREAD

**Issue by danthegoodman1** [pennersr/shove#7]
I think it would be really useful to provide more docs about the redis queue support in the readme, as that is the biggest feature for me.

For example, what do I need to do to add an item to the redis queue? What is the stream name?

**Comment by danthegoodman1** [comment]
My apologies, I assumed it was using redis streams. I see it’s using BRPOPLPUSH now (maybe supporting evidence about adding docs lol)

**Comment by pennersr** [comment]
Here's an example -- hope that helps: 453f5ee062e4fb288a453ca32c95a54cff521cec
